### ISSUE TITLE
Azure AD integration

### ISSUE THREAD

**Issue by lingamg** [Azure-Samples/ms-identity-java-daemon#10]
While trying to get the user details from MSAD i am getting the below error message.

10:18:34,437 ERROR [stderr] (default task-10) java.lang.NullPointerException
 
10:18:34,439 ERROR [stderr] (default task-10)     at com.microsoft.aad.msal4j.AuthenticationResultSupplier.logException(AuthenticationResultSupplier.java:139)
 
10:18:34,440 ERROR [stderr] (default task-10)     at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:88)
 
10:18:34,440 ERROR [stderr] (default task-10)     at com.microsoft.aad.msal4j.AuthenticationResultSupplier.get(AuthenticationResultSupplier.java:17)
 
10:18:34,441 ERROR [stderr] (default task-10)     at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
 
10:18:34,442 ERROR [stderr] (default task-10)     at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
 
10:18:34,442 ERROR [stderr] (default task-10)     at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
 
10:18:34,443 ERROR [stderr] (default task-10)     at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
 
10:18:34,443 ERROR [stderr] (default task-10)     at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
 
10:18:34,444 ERROR [stderr] (default task-10)     at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
 
10:18:34,445 INFO  [stdout] (default task-10) null

**Comment by Avery-Dunn** [comment]
Hello @lingamg : I'm trying to recreate your null pointer exception, could you provide some more info:
- In this repo, there is a sample showing how to use an app secret and a sample showing how to use a certificate. Which one were you trying when you had this issue? If you haven't already, could you try the other one to see if they both have this issue?
- Was that the entire error message? Are you able to debug it a bit to find what exactly is null? If I'm understanding your error output correctly, line 139 of `AuthenticationResultSupplier` is just an if-statement checking if an exception is an instance of `MsalClientException`, and it'd be really weird for an exception itself to be null.

**Comment by Avery-Dunn** [comment]
Closing due to inactivity. If you're still having issues or have any related questions, feel free to re-open this thread.
